source 'https://rubygems.org'

gem 'json'
gem 'rack', '~> 1.6.0'
gem 'sinatra'
gem 'sinatra-websocket'
gem 'redis'
gem 'bcrypt'
gem 'browser'

group :development, :test do
  gem 'awesome_print'
  gem 'pry'
  gem 'rspec'
  gem 'rack-test', require: 'rack/test'
  gem 'simplecov', require: false
end
