source 'https://rubygems.org'

gem 'json'
gem 'rack', '~> 1.6.0'
gem 'sinatra'
gem 'sinatra-websocket'
gem 'redis'
gem 'bcrypt'
gem 'browser'
gem 'google-api-client', '>= 0.8.2',
  :require => ['google/api_client', 'google/api_client/auth/installed_app']

group :development, :test do
  gem 'awesome_print'
  gem 'pry'
  gem 'rspec'
  gem 'rack-test', require: 'rack/test'
  gem 'simplecov', require: false
end
