source 'https://rubygems.org'

gem 'rack', '~> 1.6.0'
gem 'sinatra'
gem 'sinatra-websocket'
gem 'redis'
gem 'warden'
gem 'bcrypt'

group :development, :test do
  gem 'awesome_print'
  gem 'pry'
  gem 'rspec'
  gem 'rack-test'
  gem 'simplecov', require: false
end
