require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec) do |spec|
  spec.pattern = 'spec/**/*_spec.rb'
end

RSpec::Core::RakeTask.new(:coverage) do |spec|
  spec.pattern = 'spec/**/*_spec.rb'
end

task :run do
  exec("bundle exec thin start -p 9393 -V -D")
end

task :adduser do
  require 'yaml'
  require_relative 'app/main'
  app = RoundTable::API.new

  user_json = {
    :password => BCrypt::Password.create("swordfish"),
    :space => "default"
  }.to_json

  app.helpers.redis.set('auth_user_user', user_json)
end

task :default => :run
